# Generated by Django 3.2.7 on 2021-09-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='open',
            field=models.BooleanField(default=0, verbose_name='Статус открытия'),
        ),
    ]
